engines:
  shellcheck:
    enabled: true
    checks:
      SC2034:
        enabled: false
      SC2154:
        enabled: false
      SC1090:
        enabled: false
      SC2155:
        enabled: false
      SC2015:
        enabled: false
      SC2119:
        enabled: false
      SC2162:
        enabled: false

ratings:
   paths:
     - "SOURCES/kaosv"
     - "SOURCES/supervisor"
