language: bash

sudo: false

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

env:
  SHELLCHECK_OPTS='-e SC2034 -e SC2181 -e SC2015 -e SC2154'

script:
 - bash -c 'shopt -s globstar; shellcheck SOURCES/kaosv'
 - bash -c 'shopt -s globstar; shellcheck SOURCES/supervisor'

matrix:
  fast_finish: true
