#!/usr/bin/env bash
# shellcheck disable=SC2034

################################################################################

APP="KAOSv Supervisor"
VER="1.1.1"

INIT_DIR="/etc/init.d"

################################################################################

service_name=""

################################################################################

main() {
  local name pid_file lock_file pid

  name="$1"
  pid_file="$2"
  lock_file="$3"

  [[ $(id -u) != "0" ]] && exit 1
  [[ $# -ne 3 ]] && exit 2

  service_name="$name"

  if [[ ! -e "$INIT_DIR/$service_name" ]] ; then
    log "Can't find init script for service"
    exit 3
  fi

  [[ ! -e "$lock_file" ]] && exit 0

  if [[ -e "$pid_file" ]] ; then
    pid=$(cat "$pid_file")
    [[ -e "/proc/$pid" ]] && exit 0
  fi
  
  log "Service is dead, restarting..."
  
  restartService

  exit $?
}

restartService() {
  "$INIT_DIR/$service_name" restart &> /dev/null
  return $?
}

log() {
  echo "$*" | logger -i -t "${service_name}(kaosv-supervisor)"
}

################################################################################

main "$@"
